### ISSUE TITLE
GRES vs. TRES

### ISSUE THREAD

**Issue by jdmakey** [ericblau/ipf-xsede#12]
The IPF 1.6 compute service for SDSC's Expanse resource was logging this error:
```
2021-02-17 11:21:04,478 - ipf.glue2.slurm.ExecutionEnvironmentsStep - DEBUG - step-8 - running scontrol show reservation
Process AcceleratorEnvironmentsStep-115:176262:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/xdinfo/.local/lib/python3.6/site-packages/ipf/glue2/accelerator_environment.py", line 59, in run
    host_groups = self._run()
  File "/home/xdinfo/.local/lib/python3.6/site-packages/ipf/glue2/slurm.py", line 717, in _run
    nodes = list(filter(self._goodHost,list(map(self._getNode,node_strs))))
  File "/home/xdinfo/.local/lib/python3.6/site-packages/ipf/glue2/slurm.py", line 824, in _getNode
    node.UsedAcceleratorSlots = int(greslist[2])
ValueError: invalid literal for int() with base 10: 'c5'
```
because it was mis-parsing the GRES details of this AWS node:
```
$ scontrol show node -d exp-112-01
NodeName=exp-112-01 CoresPerSocket=4
   CPUAlloc=0 CPUTot=8 CPULoad=N/A
   AvailableFeatures=c5.2xlarge
   ActiveFeatures=c5.2xlarge
   Gres=vcpu:c5:8
   GresDrain=N/A
   GresUsed=gpu:0,vcpu:c5:0
   NodeAddr=exp-112-01 NodeHostName=exp-112-01 Port=0
   RealMemory=15200 AllocMem=0 FreeMem=N/A Sockets=1 Boards=1
   State=DOWN*+CLOUD ThreadsPerCore=2 TmpDisk=0 Weight=1 Owner=N/A MCS_label=N/A
   Partitions=aws
   BootTime=None SlurmdStartTime=None
   CfgTRES=cpu=8,mem=15200M,billing=8
   AllocTRES=
   CapWatts=n/a
   CurrentWatts=0 AveWatts=0
   ExtSensorsJoules=n/s ExtSensorsWatts=0 ExtSensorsTemp=n/s
   Reason=Not responding [root@2020-11-02T21:54:57]
```
In the `GresUsed=gpu:0,vcpu:c5:0` line IPF was trying to interpret `c5` instead of the final zero as an integer.  For the variations shown by `scontrol show node -d | grep GresUsed | sort | uniq -c`:
```
 732 GresUsed=gpu:0,vcpu:0
  80 GresUsed=gpu:0,vcpu:c5:0
  16 GresUsed=gpu:0,vcpu:t3:0
  64 GresUsed=gpu:AMZN_V100:0(IDX:N/A),vcpu:0
  14 GresUsed=gpu:v100:0(IDX:N/A),vcpu:0
   7 GresUsed=gpu:v100:1(IDX:0),vcpu:0
   2 GresUsed=gpu:v100:1(IDX:1),vcpu:0
   1 GresUsed=gpu:v100:1(IDX:3),vcpu:0
  10 GresUsed=gpu:v100:2(IDX:0-1),vcpu:0
  18 GresUsed=gpu:v100:4(IDX:0-3),vcpu:0
```
using the last colon-separated column seems correct so I fixed the problem with this patch:
```
--- lib/python3.6/site-packages/ipf/glue2/slurm.py.old 2021-01-20 09:36:22 -0800
+++ lib/python3.6/site-packages/ipf/glue2/slurm.py     2021-02-17 11:27:19 -0800
@@ -821,7 +821,7 @@
             elif len(greslist) >= 3:
                 endindex = greslist[2].find("(")
                 if endindex == -1:
-                    node.UsedAcceleratorSlots = int(greslist[2])
+                    node.UsedAcceleratorSlots = int(greslist[-1])
                 else:
                     uas = greslist[2][:endindex]
                     node.UsedAcceleratorSlots = int(uas)
```
and now the IPF services are running without errors.  However, the cluster is busy and perhaps IPF should be looking at TRES data rather than GRES.  For example:
```
$ scontrol show node -d exp-1-58
NodeName=exp-1-58 Arch=x86_64 CoresPerSocket=10 
   CPUAlloc=21 CPUTot=40 CPULoad=20.99
   AvailableFeatures=exclusive,persistenceoff
   ActiveFeatures=exclusive,persistenceoff
   Gres=gpu:v100:4(S:0-1)
   GresDrain=N/A
   GresUsed=gpu:v100:4(IDX:0-3),vcpu:0
   NodeAddr=exp-1-58 NodeHostName=exp-1-58 Version=20.02.3
   OS=Linux 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 
   RealMemory=385000 AllocMem=28096 FreeMem=351686 Sockets=4 Boards=1
   MemSpecLimit=4096
   State=MIXED ThreadsPerCore=1 TmpDisk=1500000 Weight=1 Owner=N/A MCS_label=N/A
   Partitions=gpu,gpu-shared,gpu-preempt 
   BootTime=2020-11-17T07:06:52 SlurmdStartTime=2020-11-17T07:09:02
   CfgTRES=cpu=40,mem=385000M,billing=14400,gres/gpu=4
   AllocTRES=cpu=21,mem=28096M,gres/gpu=4
   CapWatts=n/a
   CurrentWatts=0 AveWatts=0
   ExtSensorsJoules=n/s ExtSensorsWatts=0 ExtSensorsTemp=n/s
```
shows a GPU node with two jobs running.  Reporting TRES data instead of GRES would be useful for this resource.

**Comment by ericblau** [comment]
GRES parsing is fixed for IPF 1.7.  We can have future discussions about TRES.
